name: TEST

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: block

      - name: Test GitHub
        run: curl -I https://github.com

      - name: Checkout
        uses: actions/checkout@v4
